name: Build and deploy static web app to Azure Web App - hephziappservicec2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Add a step to build or copy the static files (if needed)
      # For a simple static site, you may not need any build steps, just copy the files
      - name: Prepare static files
        run: |
          # Create the 'build' folder if it doesn't exist
          mkdir -p build
          # Copy all files and folders except 'build' into the 'build' directory
          shopt -s extglob
          cp -r !("build") build/ # Copy everything except the 'build' directory into 'build/'


      - name: Zip artifact for deployment
        run: zip release.zip ./build/*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: static-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: static-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_134708D20F31452F8FC4AC5CB047E530 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6DA8B502D6C844E996574D3F9E52E886 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B4EC7D8AADB04B13AAAA47AF0B4E6ABF }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hephziappservicec2'
          slot-name: 'Production'
          package: ./build
